apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-app.fullname" . }}-config
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}