# CronJob Template
# Creates a Kubernetes CronJob for scheduled tasks if enabled.
{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "base-app.fullname" . }}-cronjob
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  suspend: {{ .Values.cronjob.suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{ include "base-app.labels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{- if .Values.serviceAccount.create }}{{ .Values.serviceAccount.name | default (include "base-app.fullname" .) }}{{- else if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{- end }}
          containers:
            - name: cronjob
              image: "{{ .Values.cronjob.image.repository | default .Values.image.repository }}:{{ .Values.cronjob.image.tag | default .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- if .Values.cronjob.command }}
              command:
                {{ toYaml .Values.cronjob.command | nindent 16 }}
              {{- end }}
              {{- if .Values.cronjob.args }}
              args:
                {{ toYaml .Values.cronjob.args | nindent 16 }}
              {{- end }}
              {{- if .Values.cronjob.env }}
              env:
                {{- range .Values.cronjob.env }}
                - name: {{ .name }}
                  value: {{ quote .value }}
                {{- end }}
              {{- end }}
              {{- if .Values.envFrom }}
              envFrom:
                {{- range .Values.envFrom }}
                - {{- if .configMapRef }}
                  configMapRef:
                    name: {{ .configMapRef.name }}
                  {{- else if .secretRef }}
                  secretRef:
                    name: {{ .secretRef.name }}
                  {{- end }}
                {{- end }}
              {{- end }}
              {{- if .Values.resources }}
              resources:
                {{ toYaml .Values.resources | nindent 16 }}
              {{- end }}
              {{- if or .Values.persistence.enabled .Values.azureKeyVault.enabled }}
              volumeMounts:
                {{- if .Values.persistence.enabled }}
                - name: {{ .Values.persistence.name }}
                  mountPath: {{ .Values.persistence.mountPath }}
                {{- end }}
                {{- if .Values.azureKeyVault.enabled }}
                - name: secrets-store
                  mountPath: {{ .Values.azureKeyVault.mountPath }}
                  readOnly: true
                {{- end }}
              {{- end }}
          {{- if or .Values.azureKeyVault.enabled .Values.persistence.enabled }}
          volumes:
            {{- if .Values.azureKeyVault.enabled }}
            - name: secrets-store
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: {{ include "base-app.fullname" . }}-azure-kv
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: {{ .Values.persistence.name }}
              persistentVolumeClaim:
                claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "base-app.fullname" . }}-{{ .Values.persistence.name }}{{ end }}
            {{- end }}
          {{- end }}
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- range .Values.imagePullSecrets }}
            - name: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml .Values.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.tolerations }}
          tolerations:
            {{ toYaml .Values.tolerations | nindent 12 }}
          {{- end }}
          {{- if .Values.affinity }}
          affinity:
            {{ toYaml .Values.affinity | nindent 12 }}
          {{- end }}
{{- end }}
