{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "base-app.fullname" . }}-ingressroute
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.ingress.entryPoints }}
    - {{ . | quote }}
    {{- end }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
      kind: Rule
      services:
        - name: {{ include "base-app.fullname" . }}
          port: {{ .Values.service.port }}
  {{- if .Values.ingress.middlewares }}
  middlewares:
    {{- range .Values.ingress.middlewares }}
    - name: {{ .name }}
      namespace: {{ .namespace | default $.Release.Namespace }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- else if .Values.ingress.tls.certResolver }}
    certResolver: {{ .Values.ingress.tls.certResolver }}
    {{- end }}
  {{- end }}
{{- end }}
