# IngressRoute Template (Traefik)
# Creates a Traefik IngressRoute for the application if enabled.
{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "base-app.fullname" . }}-ingressroute
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.ingress.entryPoints }}
    - {{ . | quote }}
    {{- end }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
      kind: Rule
      services:
        - name: {{ include "base-app.fullname" . }}  # 👈 must match the `service.metadata.name`
          port: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- else if .Values.ingress.tls.certResolver }}
    certResolver: {{ .Values.ingress.tls.certResolver }}
    {{- end }}
  {{- end }}
