# PersistentVolumeClaim Template
# Creates a PVC for persistence if enabled and no existing claim is provided.
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "base-app.fullname" . }}-{{ .Values.persistence.name }}
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
spec:
  accessModes:
    {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
{{- end }}
