# SecretProviderClass Template (Azure Key Vault CSI)
# Defines a SecretProviderClass for Azure Key Vault integration if enabled.
{{- if .Values.azureKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "base-app.fullname" . }}-azure-kv
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
spec:
  provider: azure
  {{- if .Values.azureKeyVault.syncSecrets }}
  secretObjects:
    - secretName: {{ .Values.azureKeyVault.syncSecretName | default (printf "%s-secrets" (include "base-app.fullname" .)) }}
      type: Opaque
      data:
        {{- range .Values.azureKeyVault.secrets }}
        - objectName: {{ .objectName }}
          key: {{ .secretKey | default .objectName }}
        {{- end }}
  {{- end }}
  parameters:
    usePodIdentity: {{ .Values.azureKeyVault.usePodIdentity | quote }}
    useVMManagedIdentity: {{ .Values.azureKeyVault.useVMManagedIdentity | quote }}
    userAssignedIdentityID: "{{ .Values.azureKeyVault.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.azureKeyVault.keyVaultName }}"
    tenantId: "{{ .Values.azureKeyVault.tenantId }}"
    objects: |
      array:
      {{- range .Values.azureKeyVault.secrets }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType | default "secret" }}
          {{- if .objectVersion }}
          objectVersion: {{ .objectVersion }}
          {{- else }}
          objectVersion:
          {{- end }}
      {{- end }}
{{- end }}
