apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-app.fullname" . }}-secret
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
