apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base-app.serviceAccountName" . }}
  labels:
    {{- include "base-app.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}

