apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base-app.serviceAccountName" . }}
  labels:
{{- include "base-app.labels" . | nindent 4 }}
  annotations:
{{- if .Values.serviceAccount.annotations }}
{{ .Values.serviceAccount.annotations | toYaml | nindent 4 }}
{{- end }}
automountServiceAccountToken: true
