# ServiceAccount Template
# Creates a ServiceAccount if serviceAccount.create is true.
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "base-app.fullname" .) }}
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
{{- end }}
