apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base-app.serviceAccountName" . }}
  labels:
{{ include "base-app.labels" . | indent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
automountServiceAccountToken: true
