# Default values for the base-app Helm chart.
# This file contains default values and is fully commented to describe each field.

# Global settings
nameOverride: ""        # Provide a name to override the chart's name for resources
fullnameOverride: ""    # Provide a full name for resources (if set, it overrides the release-name and chart name combo)

# Pass name space as per application
defaultNamespace: ""     # (Optional) default namespace for resource templates
namespace: dev           # Namespace to deploy into (must match the namespace in Helm --namespace flag)

# Replica count for the Deployment
replicaCount: 1           # Number of application pod replicas

# Container image configuration
image:
  repository: nginx       # Docker image repository for the application
  tag: "latest"           # Docker image tag
  pullPolicy: IfNotPresent  # Image pull policy

# Image pull secrets for private image registries
imagePullSecrets: []     # (Optional) list of Kubernetes secrets for pulling images

# Service account configuration
serviceAccount:
  create: false                      # Whether to create a new ServiceAccount
  name: ""                          # Name of the ServiceAccount to use. If not set and create=true, a name is generated
  automountServiceAccountToken: true  # Whether to auto-mount the API token for the ServiceAccount
  annotations:                      # Annotations to add to the ServiceAccount metadata
    azure.workload.identity/client-id: ""  # Client ID for Azure workload identity


# Pod annotations (e.g., for monitoring or sidecar injection)
podAnnotations: {}        # Optional annotations to add to the pod metadatahelm template charts/base-app

# Security contexts
podSecurityContext: {}    # Security context for the pod (e.g., runAsUser, fsGroup)
securityContext: {}       # Security context for the container (e.g., runAsUser, capabilities)

# Optional initContainers for pre-start setup
initContainers: []        # List of init containers to run before main container

# Service configuration
service:
  enabled: true
  type: ClusterIP         # Kubernetes service type
  port: 80                # Port to expose on the Service
  targetPort: 80          # Port on the container to target

# Container port
containerPort: 80         # Port the application container listens on

# Ingress (Traefik IngressRoute) configuration
ingress:
  enabled: true
  host: "dummy.certping.ai"     # Hostname for ingress access
  path: /                        # URL path for routing
  entryPoints:                  # Traefik entry points
    - web
  tls:
    enabled: false             # Enable TLS for ingress
    secretName: ""             # Name of the TLS secret
    certResolver: ""           # Cert resolver for Traefik's ACME
  annotations: {}              # Optional annotations for the IngressRoute

# Resources for the container
resources: {}                  # CPU and memory limits/requests

# Node scheduling configurations
nodeSelector: {}               # Node selector constraints
tolerations: []                # Pod tolerations
affinity: {}                   # Pod affinity rules

# Pod DNS configuration
priorityClassName: ""          # Optional priority class for pod scheduling
dnsPolicy: ClusterFirst        # DNS policy for the pod
dnsConfig: {}                  # Optional custom DNS config

topologySpreadConstraints: []  # Topology spread rules (optional)

# Environment variables for the container
env: []                        # List of direct env vars: [{name: FOO, value: BAR}]
envFrom: []                    # References to ConfigMaps or Secrets for env vars

# Environment source for ConfigMap and Secret (merged into envFrom)
configEnvFrom: ""              # (Optional) Name of ConfigMap to import env vars
secretEnvFrom: ""              # (Optional) Name of Secret to import env vars

# Command and arguments override
command: []                    # Override default entrypoint command
args: []                       # Override default args passed to the command

# Grace period for pod termination
terminationGracePeriodSeconds: 30  # Number of seconds to wait before killing pod

# Liveness probe
livenessProbe:
  enabled: true
  path: /
  port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Readiness probe
readinessProbe:
  enabled: true
  path: /
  port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Lifecycle hooks (optional)
lifecycle: {}  # Example: { preStop: { exec: { command: ["/bin/sh", "-c", "sleep 5"] } } }

# Persistent Volume Claim (PVC) configuration
persistence:
  enabled: false
  name: data
  existingClaim: ""
  storageClass: ""
  accessModes: ["ReadWriteOnce"]
  size: 1Gi
  mountPath: "/data"

# ConfigMap volume mount
configMount:
  enabled: false
  name: ""                  # Name of existing ConfigMap to mount at /etc/config

# Secret volume mount
secretMount:
  enabled: false
  name: ""                  # Name of existing Secret to mount at /etc/secrets

# Extra volumes and mounts
extraVolumes: []              # List of additional volumes to mount
extraVolumeMounts: []         # List of volumeMounts for above volumes

# Azure Key Vault CSI driver integration
azureKeyVault:
  enabled: false
  usePodIdentity: false
  useVMManagedIdentity: false
  userAssignedIdentityID: ""
  keyVaultName: ""
  tenantId: ""
  secrets: []
  mountPath: "/mnt/secrets"
  syncSecrets: false
  syncSecretName: ""

# ConfigMap-based env vars (example)
config:
  APP_MODE: production
  API_URL: https://dummy.certping.com

# Secret-based env vars (example)
secret:
  DB_PASSWORD: "s3cr3t"
  API_KEY: "abc123"

# Horizontal Pod Autoscaler (HPA) configuration
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: null

# Job config
job:
  enabled: false
  image:
    repository: ""
    tag: ""
  command: []
  args: []
  env: []
  restartPolicy: OnFailure
  backoffLimit: 6
  completions: 1
  parallelism: 1

# CronJob config
cronjob:
  enabled: false
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Allow
  suspend: false
  image:
    repository: ""
    tag: ""
  command: []
  args: []
  env: []
