name: Release Charts
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: azure-prod-runner-vmss
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: latest
      - name: Package chart
        run: |
          helm lint charts/base-app
          helm package charts/base-app
      - name: Helm Dry-Run Render Templates
        run: |
          helm template my-release charts/base-app -f charts/base-app/values.yaml
      # ✅ Azure login and AKS kubeconfig setup
      - name: Configure kubectl
        id: configure-kube
        run: |
          az login --identity
          az aks get-credentials --name certping-aks-dev --resource-group certping-infra-dev --overwrite-existing

      - uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.0.24"

      - name: setup kubectl for AKS
        id: setup-kubectl1
        run: |
          export KUBECONFIG=~/.kube/config
          kubelogin convert-kubeconfig -l msi
      - name: Helm Template Dry Run (Render Only)
        run: |
          helm upgrade --install dry-run-release charts/base-app \
              --namespace default \
              -f charts/base-app/values.yaml \
              --dry-run --debug
