name: Release Charts
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: azure-prod-runner-vmss
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: latest
      - name: Package chart
        run: |
          helm lint charts/base-app
          helm package charts/base-app
