name: Release Charts
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Package chart
        run: |
          helm lint charts/base-app
          helm package charts/base-app
