name: Release Charts

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: azure-prod-runner-vmss
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: latest  # You can pin version for consistency

      - name: Lint Helm Chart
        run: |
          helm lint charts/base-app

      - name: Package Helm Chart
        run: |
          helm package charts/base-app

      - name: Render Templates (Static Check)
        run: |
          helm template my-release charts/base-app -f charts/base-app/values.yaml

      - name: Azure Login (MSI)
        run: |
          az login --identity

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --name certping-aks-dev --resource-group certping-infra-dev --overwrite-existing

      - name: Install kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.0.24"

      - name: Convert kubeconfig for MSI
        run: |
          export KUBECONFIG=~/.kube/config
          kubelogin convert-kubeconfig -l msi

      - name: Helm Upgrade (Dry-Run Render Test)
        run: |
          helm upgrade --install dry-run-release charts/base-app \
              --namespace dev \
              -f charts/base-app/values.yaml \
              --dry-run --debug
      # - name: Bump Chart Version
      #   run: |
      #     CHART_YAML="charts/base-app/Chart.yaml"
      #     CURRENT_VERSION=$(yq '.version' $CHART_YAML)
      #     echo "Current version: $CURRENT_VERSION"
          
      #     # Extract major, minor, patch
      #     IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
      #     PATCH_NEXT=$((patch + 1))
      #     NEW_VERSION="${major}.${minor}.${PATCH_NEXT}"
          
      #     echo "Bumping to version: $NEW_VERSION"
      #     yq eval ".version = \"${NEW_VERSION}\"" -i $CHART_YAML
      - name: Package and index Helm chart
        run: |
          mkdir -p docs
          helm lint charts/base-app
          helm package charts/base-app --destination docs
          if [ -f docs/index.yaml ]; then
            helm repo index docs --url https://seaionl-dev.github.io/helm-universal-chart --merge docs/index.yaml
          else
            helm repo index docs --url https://seaionl-dev.github.io/helm-universal-chart
          fi

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
